name: assignment
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: rootshell <email@example.com>

environment:
  sdk: '>=2.7.0'

dependencies:
  pointycastle: ^1.0.2

dev_dependencies:
  test: ^1.15.3
